# coding: utf-8
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()



t_kidney_cancer = db.Table(
    'kidney_cancer',
    db.Column('DATE ADDED TO CATALOG', db.String(255)),
    db.Column('PUBMEDID', db.String(255)),
    db.Column('FIRST AUTHOR', db.String(255)),
    db.Column('DATE', db.String(255)),
    db.Column('JOURNAL', db.String(255)),
    db.Column('LINK', db.String(255)),
    db.Column('STUDY', db.String(255)),
    db.Column('DISEASE/TRAIT', db.String(255)),
    db.Column('INITIAL SAMPLE SIZE', db.String(255)),
    db.Column('REPLICATION SAMPLE SIZE', db.String(255)),
    db.Column('REGION', db.String(255)),
    db.Column('CHR_ID', db.String(255)),
    db.Column('CHR_POS', db.String(255)),
    db.Column('REPORTED GENE(S)', db.String(255)),
    db.Column('MAPPED_GENE', db.String(255)),
    db.Column('UPSTREAM_GENE_ID', db.String(255)),
    db.Column('DOWNSTREAM_GENE_ID', db.String(255)),
    db.Column('SNP_GENE_IDS', db.String(255)),
    db.Column('UPSTREAM_GENE_DISTANCE', db.String(255)),
    db.Column('DOWNSTREAM_GENE_DISTANCE', db.String(255)),
    db.Column('STRONGEST SNP-RISK ALLELE', db.String(255)),
    db.Column('SNPS', db.String(255)),
    db.Column('MERGED', db.String(255)),
    db.Column('SNP_ID_CURRENT', db.String(255)),
    db.Column('CONTEXT', db.String(255)),
    db.Column('INTERGENIC', db.String(255)),
    db.Column('RISK ALLELE FREQUENCY', db.String(255)),
    db.Column('P-VALUE', db.String(255)),
    db.Column('PVALUE_MLOG', db.String(255)),
    db.Column('P-VALUE (TEXT)', db.String(255)),
    db.Column('OR or BETA', db.String(255)),
    db.Column('95% CI (TEXT)', db.String(255)),
    db.Column('PLATFORM [SNPS PASSING QC]', db.String(255)),
    db.Column('CNV', db.String(255)),
    db.Column('MAPPED_TRAIT', db.String(255)),
    db.Column('MAPPED_TRAIT_URI', db.String(255)),
    db.Column('STUDY ACCESSION', db.String(255)),
    db.Column('GENOTYPING TECHNOLOGY', db.String(255))
)



t_kidney_disease = db.Table(
    'kidney_disease',
    db.Column('DATE ADDED TO CATALOG', db.Text),
    db.Column('PUBMEDID', db.Text),
    db.Column('FIRST AUTHOR', db.Text),
    db.Column('DATE', db.Text),
    db.Column('JOURNAL', db.Text),
    db.Column('LINK', db.Text),
    db.Column('STUDY', db.Text),
    db.Column('DISEASE/TRAIT', db.Text),
    db.Column('INITIAL SAMPLE SIZE', db.Text),
    db.Column('REPLICATION SAMPLE SIZE', db.Text),
    db.Column('REGION', db.Text),
    db.Column('CHR_ID', db.Text),
    db.Column('CHR_POS', db.Text),
    db.Column('REPORTED GENE(S)', db.Text),
    db.Column('MAPPED_GENE', db.Text),
    db.Column('UPSTREAM_GENE_ID', db.Text),
    db.Column('DOWNSTREAM_GENE_ID', db.Text),
    db.Column('SNP_GENE_IDS', db.Text),
    db.Column('UPSTREAM_GENE_DISTANCE', db.Text),
    db.Column('DOWNSTREAM_GENE_DISTANCE', db.Text),
    db.Column('STRONGEST SNP-RISK ALLELE', db.Text),
    db.Column('SNPS', db.Text),
    db.Column('MERGED', db.Text),
    db.Column('SNP_ID_CURRENT', db.Text),
    db.Column('CONTEXT', db.Text),
    db.Column('INTERGENIC', db.Text),
    db.Column('RISK ALLELE FREQUENCY', db.Text),
    db.Column('P-VALUE', db.Text),
    db.Column('PVALUE_MLOG', db.Text),
    db.Column('P-VALUE (TEXT)', db.Text),
    db.Column('OR or BETA', db.Text),
    db.Column('95% CI (TEXT)', db.Text),
    db.Column('PLATFORM [SNPS PASSING QC]', db.Text),
    db.Column('CNV', db.Text),
    db.Column('MAPPED_TRAIT', db.Text),
    db.Column('MAPPED_TRAIT_URI', db.Text),
    db.Column('STUDY ACCESSION', db.Text),
    db.Column('GENOTYPING TECHNOLOGY', db.Text)
)
